### ISSUE TITLE
Password for VCL.exe

### ISSUE THREAD

**Issue by AS4GamingAK** [rdebath/viruses#3]
Hi! I was unzipping everything and while unzipping NMVCL.ZIP to NMVCL, It asked for a password (as you mentioned in your last commit. I can't find the password for the file in this repo. Please share the password with me.

Regards

Find the corresponding screenshot below:-
![Screenshot 2024-09-02 082140](https://github.com/user-attachments/assets/f6658865-aa8c-418e-91b5-6e2db1faffb3)

**Comment by AS4GamingAK** [comment]
Sorry, I thought I found the pwd
The Password Is
Chiba City
this doesn't work. I tried pasting the whole thing under the first line. Please check. @rdebath

**Comment by rdebath** [comment]
As stated in the `INSTALL.txt` you use the `INSTALL.EXE` and `pkunzip.exe` programs, not some other UNZIP.

>The .ZIP file (NMVCL.ZIP) will NOT unzip from the DOS
prompt.

Also it is a DOS file. The Ctrl-Z is a common file terminator, not part of the password.
